#import "T2Overlay.h"
#import "T2Runtime.h"
@interface T2Overlay()<UITableViewDataSource,UITableViewDelegate>
@property UIWindow *window; @property UITableView *table; @property UISegmentedControl *tabs; @property NSArray *rows; @property UILabel *titleLabel;
@end
@implementation T2Overlay
+ (instancetype)shared { static id x; static dispatch_once_t once; dispatch_once(&once,^{x=[self new];}); return x; }
- (void)install { dispatch_async(dispatch_get_main_queue(), ^{
    if(self.window) return; CGRect b=UIScreen.mainScreen.bounds; self.window=[[UIWindow alloc]initWithFrame:b]; self.window.windowLevel=UIWindowLevelAlert+77; self.window.backgroundColor=UIColor.clearColor;
    UIViewController *vc=[UIViewController new]; vc.view.backgroundColor=[UIColor colorWithWhite:0.03 alpha:.94]; self.window.rootViewController=vc;
    UIButton *bubble=[UIButton buttonWithType:UIButtonTypeSystem]; bubble.frame=CGRectMake(14,70,58,58); bubble.layer.cornerRadius=29; bubble.backgroundColor=[UIColor colorWithRed:.32 green:.22 blue:.95 alpha:1]; [bubble setTitle:@"t2" forState:0]; [bubble setTitleColor:UIColor.whiteColor forState:0]; bubble.titleLabel.font=[UIFont boldSystemFontOfSize:20]; [bubble addTarget:self action:@selector(toggle:) forControlEvents:UIControlEventTouchUpInside]; [vc.view addSubview:bubble];
    UIView *panel=[[UIView alloc]initWithFrame:CGRectMake(12,140,b.size.width-24,b.size.height-165)]; panel.tag=22; panel.backgroundColor=[UIColor colorWithWhite:.055 alpha:.98]; panel.layer.cornerRadius=18; panel.hidden=YES; [vc.view addSubview:panel];
    UILabel *h=[[UILabel alloc]initWithFrame:CGRectMake(16,10,panel.bounds.size.width-32,36)]; h.text=@"take2 • الفحص الذكي"; h.textColor=UIColor.whiteColor; h.textAlignment=NSTextAlignmentRight; h.font=[UIFont boldSystemFontOfSize:20]; [panel addSubview:h]; self.titleLabel=h;
    self.tabs=[[UISegmentedControl alloc]initWithItems:@[@"المميزات",@"القيم",@"بحث",@"مراقبة"]]; self.tabs.frame=CGRectMake(12,52,panel.bounds.size.width-24,34); self.tabs.selectedSegmentIndex=0; [self.tabs addTarget:self action:@selector(reload) forControlEvents:UIControlEventValueChanged]; [panel addSubview:self.tabs];
    self.table=[[UITableView alloc]initWithFrame:CGRectMake(0,96,panel.bounds.size.width,panel.bounds.size.height-96) style:UITableViewStylePlain]; self.table.backgroundColor=UIColor.clearColor; self.table.dataSource=self; self.table.delegate=self; self.table.rowHeight=76; [panel addSubview:self.table];
    self.window.hidden=NO; [self reload];
}); }
- (void)toggle:(UIButton*)b { UIView *p=[b.superview viewWithTag:22]; p.hidden=!p.hidden; }
- (void)reload { NSInteger i=self.tabs.selectedSegmentIndex; if(i==0) self.rows=[[T2Runtime shared] smartFeatures]; else self.rows=[[T2Runtime shared] editableValues]; self.titleLabel.text=i==0?@"take2 • المميزات المكتشفة":(i==1?@"take2 • القيم القابلة للتغيير":(i==2?@"take2 • البحث بالقيمة":@"take2 • المراقبة")); [self.table reloadData]; }
- (NSInteger)tableView:(UITableView*)t numberOfRowsInSection:(NSInteger)s{return self.rows.count;}
- (UITableViewCell*)tableView:(UITableView*)t cellForRowAtIndexPath:(NSIndexPath*)p { UITableViewCell *c=[t dequeueReusableCellWithIdentifier:@"x"]; if(!c)c=[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:@"x"]; NSDictionary *d=self.rows[p.row]; c.backgroundColor=UIColor.clearColor; c.textLabel.textColor=UIColor.whiteColor; c.detailTextLabel.textColor=[UIColor colorWithWhite:.7 alpha:1]; c.textLabel.textAlignment=NSTextAlignmentRight; c.detailTextLabel.textAlignment=NSTextAlignmentRight; c.textLabel.text=[NSString stringWithFormat:@"%@  •  %@",d[@"ar"],d[@"value"]]; c.detailTextLabel.text=[NSString stringWithFormat:@"%@.%@  | الثقة: %@ | %@",d[@"class"],d[@"name"],d[@"confidence"],[d[@"writable"] boolValue]?@"قابل للتعديل":@"قراءة فقط"]; return c; }
- (void)tableView:(UITableView*)t didSelectRowAtIndexPath:(NSIndexPath*)p { NSDictionary *d=self.rows[p.row]; if(![d[@"writable"] boolValue]) return; UIAlertController *a=[UIAlertController alertControllerWithTitle:d[@"ar"] message:[NSString stringWithFormat:@"%@.%@\nالثقة: %@",d[@"class"],d[@"name"],d[@"confidence"]] preferredStyle:UIAlertControllerStyleAlert]; [a addTextFieldWithConfigurationHandler:^(UITextField *f){f.keyboardType=UIKeyboardTypeDecimalPad;f.text=[d[@"value"] stringValue];}]; [a addAction:[UIAlertAction actionWithTitle:@"إلغاء" style:UIAlertActionStyleCancel handler:nil]]; [a addAction:[UIAlertAction actionWithTitle:@"تطبيق محلي" style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction *x){NSString *e=nil; [[T2Runtime shared] setObject:d[@"object"] key:d[@"name"] number:@(a.textFields.firstObject.text.doubleValue) error:&e]; [self reload];}]]; [self.window.rootViewController presentViewController:a animated:YES completion:nil]; }
@end
